<?php

namespace Yousef\app\providers;

use Illuminate\Support\ServiceProvider;
use Yousef\structure\facade\ApiImplementation;

class ApiServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->bind("Api", function () {
            return new ApiImplementation();
        });
    }
    public function boot()
    {
        $this->publishes([
            __DIR__.'/../../config/api.php'
        ]);
    }
}