<?php

namespace yousefdev20\Api;

use Illuminate\Support\ServiceProvider;
use YousefDev20\Api\Structure\Facade\Api;
use YousefDev20\Api\Structure\facade\ApiImplementation;

class ApiServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->bind(Api::class, function () {
            return new ApiImplementation();
        });
    }
    public function boot()
    {
        $this->publishes([
            __DIR__.'/../../config/api.php'
        ]);
    }
}